// <auto-generated />
using System;
using L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    [Migration("20260130221352_AddTradeOffers")]
    partial class AddTradeOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousOwners")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.TradeOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferedGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferedGameId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RequestedGameId");

                    b.HasIndex("RequesterUserId");

                    b.ToTable("TradeOffers");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.Game", b =>
                {
                    b.HasOne("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.User", "Owner")
                        .WithMany("Games")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.TradeOffer", b =>
                {
                    b.HasOne("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.Game", "OfferedGame")
                        .WithMany("OfferedInOffers")
                        .HasForeignKey("OfferedGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.User", "OwnerUser")
                        .WithMany("ReceivedOffers")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.Game", "RequestedGame")
                        .WithMany("RequestedInOffers")
                        .HasForeignKey("RequestedGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.User", "RequesterUser")
                        .WithMany("SentOffers")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfferedGame");

                    b.Navigation("OwnerUser");

                    b.Navigation("RequestedGame");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.Game", b =>
                {
                    b.Navigation("OfferedInOffers");

                    b.Navigation("RequestedInOffers");
                });

            modelBuilder.Entity("L1_Retro_Video_Game_Exchange_Hypermedia_Rest_API.Models.User", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("ReceivedOffers");

                    b.Navigation("SentOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
